package oth.shipeditor.representation.ship;

/**
 * @author Ontheheavens
 * @since 30.06.2023
 */
public enum ShipTypeHints {
    FREIGHTER,
    TANKER,
    LINER,
    TRANSPORT,
    CIVILIAN,
    CARRIER,
    COMBAT,
    NO_AUTO_ESCORT,
    UNBOARDABLE,
    STATION,
    SHIP_WITH_MODULES,
    HIDE_IN_CODEX,
    UNDER_PARENT,
    INDEPENDENT_ROTATION,
    ALWAYS_PANIC,
    WEAPONS_FRONT_TO_BACK,
    WEAPONS_BACK_TO_FRONT,
    DO_NOT_SHOW_MODULES_IN_FLEET_LIST,
    RENDER_ENGINES_BELOW_HULL,
    NEVER_DODGE_MISSILES,
    MISSILE_HARDPOINTS_ROTATE,
    NO_NEURAL_LINK,
    PHASE,
    PLAY_FIGHTER_OVERLOAD_SOUNDS,
}
